### PR TITLE
Require Python 3.8+

### PR DESCRIPTION
**Pull request by justinmayer**
- Require Python 3.8+ (Python 3.7 soon goes [end-of-life](https://endoflife.date/python))
- Update linter dependency versions
- Minor improvements to Invoke task console output
- Improve package classifier metadata handling
- Remove upper bounds on Pelican & Markdown packages
- Use built-in Black profile for isort

### CODE REVIEW

**Comment by justinmayer** [comment]
@davidag: CI is failing here because `poetry.lock` is out-of-date. Obviously I can update it and push another commit to this PR, but in my opinion committing `poetry.lock` to the repo for this kind of project is overkill and adds undue maintenance overhead without much benefit, which is why nearly all the other repositories here omit `poetry.lock` and Git-ignore it. See also: https://github.com/pelican-plugins/linkbacks/pull/8#issuecomment-1401453014

That said, let me know which approach you prefer, and I'll handle it accordingly in this PR. 😊

**Comment by justinmayer** [comment]
Hey David. Any thoughts about my `poetry.lock` question and about this PR in general?

**Comment by davidag** [comment]
> Hey David. Any thoughts about my `poetry.lock` question and about this PR in general?

Hey @justinmayer, thanks for the PR, let me review it this weekend 🙏🏼

**Comment by davidag** [comment]
@justinmayer I have removed `poetry.lock` and fixed the `setup-python` github action that used it. Do you think we should make a new release?

**Comment by justinmayer** [comment]
@davidag: Nice work. In terms of end-user functionality, I'm not sure anything has changed, and thus I'm not sure what value folks would get from a new release at this juncture. But once Python 3.7 is officially EOL in June, that seems like a good time to once again consider a new release. Just my two cents, of course! 😊

**Comment by davidag** [comment]
@justinmayer Perfect, makes sense to me 👌🏼 I created #14 and will merge this now. Thanks for your help! 🙏🏼

**Pull request merged**
